import Head from 'next/head'
import Image from 'next/image'
import Navbar from '../components/navbar'
import styles from '../styles/index.module.css'
import {useCookies} from 'react-cookie'
import { useRouter } from 'next/router'

import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { faPlus } from '@fortawesome/free-solid-svg-icons';




export default function Index() {
  const [cookie, setCookie, removeCookie]= useCookies()
  const router = useRouter();
  const reRouteLoanPage = async(event) => {

  

    router.push('/bankpage')
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar></Navbar>

      <div>
        <div className="bg-violet-100" id='home'>
          <div className={`${styles['part-1']}`}>
            <p className={`${styles['main-text']}`}>
              <span className={`${styles['line-1']}`}>Welcome To</span>
              <span className={`${styles['line-2']}`}>ST Financials</span>
            </p>

            <span className="transition delay-150 duration-300 ease-in-out" ><img src='/ppl2.png' className={styles.img}/></span>
          </div>

          {!cookie.token && (
            <div className={styles.new}>
              <p>Already a User? <a href='/Login' className={styles.highlight}>Login</a></p>
              <p>New User? <a href='/Signup' className={styles.highlight}>Signup</a></p>
            </div>
          )}
          
          {cookie.token && (
            <div className={`${styles['part-2']}`}>
              <button onClick={reRouteLoanPage} className={styles.apply}><FontAwesomeIcon icon={faPlus} className={styles.icon} /><span className={styles.prompt}>Apply Loan</span></button>
            </div>
          )}

        </div>

        <div className={styles.features}>

          <h className={`${styles['feature-head']}`}>Features</h>
          <div className={`${styles['feature-list']}`}>

            <div className={styles.row}>
              <div className={`${styles['tile-1']}`}>
                <div className={styles.head}>Financial Aid</div>
                <div className={styles.para}>
                  Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam quis massa gravida, dapibus dolor quis, feugiat erat. Ut fringilla a neque sed efficitur. In ipsum purus, vehicula sit amet rhoncus fermentum, posuere at risus.
                </div>
              </div>
              <img src='/loans.png' className={`${styles['tileimg-1']}`}></img>
            </div>

            <div className={styles.row}>
              <img src='/security.png' className={`${styles['tileimg-2']}`}></img>
              <div className={`${styles['tile-2']}`}>
                <div className={styles.head}>Secure</div>
                <div className={styles.para}>
                  Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam quis massa gravida, dapibus dolor quis, feugiat erat. Ut fringilla a neque sed efficitur. In ipsum purus, vehicula sit amet rhoncus fermentum, posuere at risus.
                </div>
              </div>
            </div>

            <div className={styles.row}>
              <div className={`${styles['tile-1']}`}>
                <div className={styles.head}>Services</div>
                <div className={styles.para}>
                  Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam quis massa gravida, dapibus dolor quis, feugiat erat. Ut fringilla a neque sed efficitur. In ipsum purus, vehicula sit amet rhoncus fermentum, posuere at risus.
                </div>
              </div>
              <img src='/services.png' className={`${styles['tileimg-1']}`}></img>
            </div>

            <div className={styles.row}>
              <img src='/reviews.png' className={`${styles['tileimg-2']}`}></img>
              <div className={`${styles['tile-2']}`}>
                <div className={styles.head}>Reviews</div>
                <div className={styles.para}>
                  Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam quis massa gravida, dapibus dolor quis, feugiat erat. Ut fringilla a neque sed efficitur. In ipsum purus, vehicula sit amet rhoncus fermentum, posuere at risus.
                </div>
              </div>
            </div>

            <div className={styles.separator}></div>
          </div>

        </div>

      </div>
    </div>
  )
}
